-- Ejecutar UNA vez en Supabase: SQL Editor > New query > pegar > Run.

-- 1) Tabla de productos. "data" guarda el resto de los campos del producto
--    (descripcion, precio, imagenes, especificaciones, listas, etc.).
create table if not exists public.productos (
  id          bigint generated by default as identity primary key,
  publicado   boolean not null default true,
  data        jsonb   not null default '{}'::jsonb,
  created_at  timestamptz not null default now()
);

alter table public.productos enable row level security;

-- 2) Lectura: el público solo ve lo publicado; el admin (con sesión) ve todo.
drop policy if exists "lectura publica" on public.productos;
create policy "lectura publica" on public.productos
  for select using (publicado = true or auth.role() = 'authenticated');

-- 3) Escritura: solo usuarios con sesión.
drop policy if exists "escritura admin" on public.productos;
create policy "escritura admin" on public.productos
  for all to authenticated using (true) with check (true);

-- 4) Bucket público para fotos y videos.
insert into storage.buckets (id, name, public)
values ('productos', 'productos', true)
on conflict (id) do nothing;

drop policy if exists "archivos lectura" on storage.objects;
create policy "archivos lectura" on storage.objects
  for select using (bucket_id = 'productos');

drop policy if exists "archivos escritura" on storage.objects;
create policy "archivos escritura" on storage.objects
  for all to authenticated
  using (bucket_id = 'productos') with check (bucket_id = 'productos');
